/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package matematicasGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author alfre
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    int num;
    public boolean validarEntero(String mensaje){
        try{
            num = Integer.parseInt(JOptionPane.showInputDialog(null, mensaje));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Entrada no valida, intente de nuevo.");
            return false;
        }
        return true;
    }
    double n;
    public boolean validarDouble(String mensaje){
        try{
            n = Double.parseDouble(JOptionPane.showInputDialog(null, mensaje));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Entrada no valida, intente de nuevo.");
            return false;
        }
        return true;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonFactorialInt = new javax.swing.JButton();
        jButtonFactorialDouble = new javax.swing.JButton();
        jButtonNumPrimo = new javax.swing.JButton();
        jButtonSerieE = new javax.swing.JButton();
        jButtonAñoBisiesto = new javax.swing.JButton();
        jButtonSerieT = new javax.swing.JButton();
        jButtonSeriePI = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("MENÚ");

        jButtonFactorialInt.setBackground(new java.awt.Color(0, 70, 140));
        jButtonFactorialInt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFactorialInt.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFactorialInt.setText("FACTORIAL (Int 0-12)");
        jButtonFactorialInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFactorialIntActionPerformed(evt);
            }
        });

        jButtonFactorialDouble.setBackground(new java.awt.Color(0, 70, 140));
        jButtonFactorialDouble.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFactorialDouble.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFactorialDouble.setText("FACTORIAL (Double 12+)");
        jButtonFactorialDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFactorialDoubleActionPerformed(evt);
            }
        });

        jButtonNumPrimo.setBackground(new java.awt.Color(0, 70, 140));
        jButtonNumPrimo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonNumPrimo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumPrimo.setText("NÚMERO PRIMO");
        jButtonNumPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumPrimoActionPerformed(evt);
            }
        });

        jButtonSerieE.setBackground(new java.awt.Color(0, 70, 140));
        jButtonSerieE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSerieE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSerieE.setText("SERIE E");
        jButtonSerieE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSerieEActionPerformed(evt);
            }
        });

        jButtonAñoBisiesto.setBackground(new java.awt.Color(0, 70, 140));
        jButtonAñoBisiesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAñoBisiesto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAñoBisiesto.setText("AÑO BISIESTO");
        jButtonAñoBisiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñoBisiestoActionPerformed(evt);
            }
        });

        jButtonSerieT.setBackground(new java.awt.Color(0, 70, 140));
        jButtonSerieT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSerieT.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSerieT.setText("SERIE T");
        jButtonSerieT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSerieTActionPerformed(evt);
            }
        });

        jButtonSeriePI.setBackground(new java.awt.Color(0, 70, 140));
        jButtonSeriePI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSeriePI.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeriePI.setText("SERIE PI");
        jButtonSeriePI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeriePIActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(135, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFactorialDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFactorialInt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSerieE, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSerieT, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeriePI, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jButtonFactorialInt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFactorialDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNumPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSerieE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSerieT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSeriePI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFactorialIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFactorialIntActionPerformed
        if(validarEntero("Numero:"))
            JOptionPane.showMessageDialog(null, "El resultado es: " + Matematicas.Factorial(num));
    }//GEN-LAST:event_jButtonFactorialIntActionPerformed

    private void jButtonFactorialDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFactorialDoubleActionPerformed
        if(validarDouble("Numero:"))
            JOptionPane.showMessageDialog(null, "El resultado es: " + Matematicas.Factorial(n));
    }//GEN-LAST:event_jButtonFactorialDoubleActionPerformed

    private void jButtonNumPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumPrimoActionPerformed
        if(validarEntero("Numero:")){
            if(Matematicas.esPrimo1(num))
                JOptionPane.showMessageDialog(null, "El numero es primo");
            else
                JOptionPane.showMessageDialog(null, "El numero no es primo");
        }
    }//GEN-LAST:event_jButtonNumPrimoActionPerformed

    private void jButtonSerieEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSerieEActionPerformed
        if(validarDouble("Numero:"))
            JOptionPane.showMessageDialog(null, "El resultado es: " + Matematicas.serieE(num));
    }//GEN-LAST:event_jButtonSerieEActionPerformed

    private void jButtonAñoBisiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñoBisiestoActionPerformed
        if(validarEntero("Año:")){
            if(Matematicas.esBisiesto(num))
                JOptionPane.showMessageDialog(null, "El año es bisiesto" );
            else
                JOptionPane.showMessageDialog(null, "El año no es bisiesto" );
        }
    }//GEN-LAST:event_jButtonAñoBisiestoActionPerformed

    private void jButtonSerieTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSerieTActionPerformed
        if(validarEntero("Numero:"))
            if(validarDouble("Vueltas:"))
                JOptionPane.showMessageDialog(null, "El resultado es: " + Matematicas.serieT(num, n));
    }//GEN-LAST:event_jButtonSerieTActionPerformed

    private void jButtonSeriePIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeriePIActionPerformed
        if(validarEntero("Numero:"))
            JOptionPane.showMessageDialog(null, "El resultado es: " + Matematicas.seriePi(num));
    }//GEN-LAST:event_jButtonSeriePIActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñoBisiesto;
    private javax.swing.JButton jButtonFactorialDouble;
    private javax.swing.JButton jButtonFactorialInt;
    private javax.swing.JButton jButtonNumPrimo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSerieE;
    private javax.swing.JButton jButtonSeriePI;
    private javax.swing.JButton jButtonSerieT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
