/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package string1;

/**
 *
 * @author aa611
 */
public class menuGUI extends javax.swing.JFrame {

    char [] arregloChar;
    
    /**
     * Creates new form menuGUI
     */
    public menuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextCadena = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonAMayus = new javax.swing.JButton();
        jButtonAMinus = new javax.swing.JButton();
        jButtonNumMayus = new javax.swing.JButton();
        jButtonNumMinus = new javax.swing.JButton();
        jButtonNumDigitos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextCadena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCadenaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("CADENA:");

        jButtonAMayus.setBackground(new java.awt.Color(88, 179, 0));
        jButtonAMayus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAMayus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAMayus.setText("A MAYUSCULAS");
        jButtonAMayus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAMayusActionPerformed(evt);
            }
        });

        jButtonAMinus.setBackground(new java.awt.Color(88, 179, 0));
        jButtonAMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAMinus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAMinus.setText("A MINUSCULAS");
        jButtonAMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAMinusActionPerformed(evt);
            }
        });

        jButtonNumMayus.setBackground(new java.awt.Color(88, 179, 0));
        jButtonNumMayus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonNumMayus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumMayus.setText("# DE MAYUSCULAS");
        jButtonNumMayus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumMayusActionPerformed(evt);
            }
        });

        jButtonNumMinus.setBackground(new java.awt.Color(88, 179, 0));
        jButtonNumMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonNumMinus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumMinus.setText("# DE MINUSCULAS");
        jButtonNumMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumMinusActionPerformed(evt);
            }
        });

        jButtonNumDigitos.setBackground(new java.awt.Color(88, 179, 0));
        jButtonNumDigitos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonNumDigitos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumDigitos.setText("# DE DIGITOS");
        jButtonNumDigitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumDigitosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("RESULTADO:");

        jLabelResultado.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultado.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(30, 30, 30)
                            .addComponent(jTextCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonAMayus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNumMayus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNumMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNumDigitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAMayus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAMinus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNumMayus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNumMinus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNumDigitos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void leerYGuardar(){
        arregloChar = this.jTextCadena.getText().toCharArray();
    }
    
    private void jTextCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCadenaActionPerformed

    private void jButtonAMayusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAMayusActionPerformed
        //BOTON A MAYUSCULAS
        leerYGuardar();
        for(int i=0; i < arregloChar.length; i++){
            arregloChar[i] = Caracter.aMayuscula(arregloChar[i]);
        }
        this.jLabelResultado.setText(String.copyValueOf(arregloChar));
    }//GEN-LAST:event_jButtonAMayusActionPerformed

    private void jButtonAMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAMinusActionPerformed
        //BOTON A MINUSCULAS
        leerYGuardar();
        for(int i=0; i < arregloChar.length; i++){
            arregloChar[i] = Caracter.aMinuscula(arregloChar[i]);
        }
        this.jLabelResultado.setText(String.copyValueOf(arregloChar));
    }//GEN-LAST:event_jButtonAMinusActionPerformed

    private void jButtonNumMayusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumMayusActionPerformed
        //BOTON # DE MAYUSCULAS
        leerYGuardar();
        int contMayus = 0;
        for(int i=0; i < arregloChar.length; i++){
            if(Caracter.esMayuscula(arregloChar[i]))
                contMayus ++;
        }
        this.jLabelResultado.setText("LA CADENA TIENE "+contMayus+" MAYUSCULAS");
    }//GEN-LAST:event_jButtonNumMayusActionPerformed

    private void jButtonNumMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumMinusActionPerformed
        //BOTON # DE MAYUSCULAS
        leerYGuardar();
        int contMinus = 0;
        for(int i=0; i < arregloChar.length; i++){
            if(Caracter.esMinuscula(arregloChar[i]))
                contMinus ++;
        }
        this.jLabelResultado.setText("LA CADENA TIENE "+contMinus+" MINUSCULAS");
        
    }//GEN-LAST:event_jButtonNumMinusActionPerformed

    private void jButtonNumDigitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumDigitosActionPerformed
        //BOTON # DE MAYUSCULAS
        leerYGuardar();
        int contDigitos = 0;
        for(int i=0; i < arregloChar.length; i++){
            if(Caracter.esDigito(arregloChar[i]))
                contDigitos ++;
        }
        this.jLabelResultado.setText("LA CADENA TIENE "+contDigitos+" DIGITOS");
    }//GEN-LAST:event_jButtonNumDigitosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAMayus;
    private javax.swing.JButton jButtonAMinus;
    private javax.swing.JButton jButtonNumDigitos;
    private javax.swing.JButton jButtonNumMayus;
    private javax.swing.JButton jButtonNumMinus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JTextField jTextCadena;
    // End of variables declaration//GEN-END:variables
}
