/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfre
 */
public class FormPila extends javax.swing.JFrame {

    /**
     * Creates new form FormPila
     */
    
    DefaultTableModel modelo;
    Pila pila;
    int cont = 0, tam = 0;
    Random random = new Random();    
    
    public FormPila() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel) jTablePila.getModel();
        jTablePila.setShowHorizontalLines(true);
        jTablePila.setShowVerticalLines(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinnerTamaño = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextDato = new javax.swing.JTextField();
        jButtonAleatorio = new javax.swing.JButton();
        jButtonLlenar = new javax.swing.JButton();
        jButtonVaciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePila = new javax.swing.JTable();
        jButtonPush = new javax.swing.JButton();
        jButtonPop = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelExtraido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("TAMAÑO DE LA PILA:");

        jSpinnerTamaño.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jSpinnerTamaño.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerTamañoStateChanged(evt);
            }
        });

        jLabel2.setText("DATO A INSERTAR:");

        jTextDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDatoActionPerformed(evt);
            }
        });

        jButtonAleatorio.setText("Aleatorio");
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });

        jButtonLlenar.setText("Llenar");
        jButtonLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLlenarActionPerformed(evt);
            }
        });

        jButtonVaciar.setText("Vaciar");

        jTablePila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePila.setTableHeader(null);
        jScrollPane1.setViewportView(jTablePila);
        if (jTablePila.getColumnModel().getColumnCount() > 0) {
            jTablePila.getColumnModel().getColumn(0).setResizable(false);
            jTablePila.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonPush.setText("PUSH");
        jButtonPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPushActionPerformed(evt);
            }
        });

        jButtonPop.setText("POP");
        jButtonPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPopActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PILA");

        jLabelExtraido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExtraido.setText("DATO EXTRAIDO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerTamaño)
                            .addComponent(jTextDato))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLlenar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVaciar))
                            .addComponent(jButtonAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPush)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelExtraido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(34, 34, 34)
                .addComponent(jButtonPop)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLlenar)
                    .addComponent(jButtonVaciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAleatorio))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButtonPush))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButtonPop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelExtraido)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerTamañoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerTamañoStateChanged
        tam = (int)this.jSpinnerTamaño.getValue();
        pila = new Pila(tam);
        modelo.setRowCount(tam);
        modelo.setValueAt("Tope", 0, 0);
        int j = 1;
        for(int i = tam-1; i > 0; i--){
            modelo.setValueAt(j++, i, 0);
        }
        
    }//GEN-LAST:event_jSpinnerTamañoStateChanged

    private void jButtonPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPushActionPerformed
        pila.push(Integer.parseInt(this.jTextDato.getText()));
        modelo.setValueAt(this.jTextDato.getText(), tam-1, 1);
        tam--;
    }//GEN-LAST:event_jButtonPushActionPerformed

    private void jButtonPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPopActionPerformed
        this.jLabelExtraido.setText("DATO EXTRAIDO: " + pila.pop());
        modelo.setValueAt(null, cont++, 1);
    }//GEN-LAST:event_jButtonPopActionPerformed

    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        this.jTextDato.setText(Integer.toString(random.nextInt(90)+10));
    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    private void jButtonLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLlenarActionPerformed
        int n;
        for(int i = 0; i < tam; i++){
            n = random.nextInt(90)+10;
            pila.push(n);
            modelo.setValueAt(n, i, 1);
        }
        
    }//GEN-LAST:event_jButtonLlenarActionPerformed

    private void jTextDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDatoActionPerformed
        this.jButtonPushActionPerformed(null);
    }//GEN-LAST:event_jTextDatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonLlenar;
    private javax.swing.JButton jButtonPop;
    private javax.swing.JButton jButtonPush;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelExtraido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerTamaño;
    private javax.swing.JTable jTablePila;
    private javax.swing.JTextField jTextDato;
    // End of variables declaration//GEN-END:variables
}
