/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vectortgui;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfre
 */
public class VectorTGUI extends javax.swing.JFrame {

    /**
     * Creates new form VectorTGUI
     */
    
    int opc;
    Random random = new Random();
    DefaultTableModel modelo;
    
    public VectorTGUI() {
        initComponents();
        modelo =  (DefaultTableModel)this.jTableVector.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioEntero = new javax.swing.JRadioButton();
        jRadioDouble = new javax.swing.JRadioButton();
        jRadioFloat = new javax.swing.JRadioButton();
        jRadioChar = new javax.swing.JRadioButton();
        jRadioString = new javax.swing.JRadioButton();
        jButtonGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVector = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMenor = new javax.swing.JLabel();
        jLabelMayor = new javax.swing.JLabel();
        jLabelPromedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("SELECCIONE EL TIPO DE DATO:");

        jRadioEntero.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jRadioEntero.setText("Entero");
        jRadioEntero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEnteroActionPerformed(evt);
            }
        });

        jRadioDouble.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jRadioDouble.setText("Double");
        jRadioDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDoubleActionPerformed(evt);
            }
        });

        jRadioFloat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jRadioFloat.setText("Float");
        jRadioFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFloatActionPerformed(evt);
            }
        });

        jRadioChar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jRadioChar.setText("Char");
        jRadioChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCharActionPerformed(evt);
            }
        });

        jRadioString.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jRadioString.setText("String");
        jRadioString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioStringActionPerformed(evt);
            }
        });

        jButtonGenerar.setBackground(new java.awt.Color(153, 0, 255));
        jButtonGenerar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonGenerar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerar.setText("GENERAR");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jTableVector.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTableVector.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VECTOR"
            }
        ));
        jScrollPane1.setViewportView(jTableVector);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("MAYOR:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("MENOR:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("PROMEDIO:");

        jLabelMenor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMenor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelMenor.setForeground(new java.awt.Color(0, 112, 14));
        jLabelMenor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenor.setOpaque(true);

        jLabelMayor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMayor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelMayor.setForeground(new java.awt.Color(0, 112, 14));
        jLabelMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMayor.setOpaque(true);

        jLabelPromedio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPromedio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelPromedio.setForeground(new java.awt.Color(0, 112, 14));
        jLabelPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPromedio.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioString)
                                    .addComponent(jRadioChar)
                                    .addComponent(jRadioFloat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jRadioDouble)
                            .addComponent(jRadioEntero)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioEntero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioDouble)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioFloat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioChar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioString)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonGenerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiar(){
        this.jRadioEntero.setSelected(false);
        this.jRadioDouble.setSelected(false);
        this.jRadioFloat.setSelected(false);
        this.jRadioChar.setSelected(false);
        this.jRadioString.setSelected(false);
    }
    
    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        
        modelo.setRowCount(0);
        
        switch(opc){
            case 1: //Entero
                VectorT<Integer> vecEnteros = new VectorT<Integer>(10);
                for(int i = 0; i < vecEnteros.tam(); i++){
                    vecEnteros.asignar(i, random.nextInt(50)+50);
                    modelo.insertRow(modelo.getRowCount(), new Object[]{vecEnteros.leer(i)});
                }
                this.jLabelMenor.setText(vecEnteros.menor()+"");
                this.jLabelMayor.setText(vecEnteros.mayor()+"");
                this.jLabelPromedio.setText(vecEnteros.promedio()+"");
                break;
                
            case 2: //Double
                VectorT<Double> vecDouble = new VectorT(random.nextInt(10));
                for(int i = 0; i < vecDouble.tam(); i++){
                    vecDouble.asignar(i, random.nextDouble()*90+10);
                    modelo.insertRow(modelo.getRowCount(), new Object[]{vecDouble.leer(i)});
                }
                this.jLabelMenor.setText(vecDouble.menor()+"");
                this.jLabelMayor.setText(vecDouble.mayor()+"");
                this.jLabelPromedio.setText(vecDouble.promedio()+"");
                break;
                
            case 3: //Float
                VectorT<Float> vecFloats = new VectorT(random.nextInt(20));
                for(int i = 0; i < vecFloats.tam(); i++){
                    vecFloats.asignar(i, random.nextFloat()*90+10);//10.0f, 99.0f
                    modelo.insertRow(modelo.getRowCount(), new Object[]{vecFloats.leer(i)});
                }
                this.jLabelMenor.setText(vecFloats.menor()+"");
                this.jLabelMayor.setText(vecFloats.mayor()+"");
                this.jLabelPromedio.setText(vecFloats.promedio()+"");
                break;
                
            case 4: //Char
                VectorT<Character> vecChar = new VectorT(random.nextInt(26)+1);
                for(int i = 0; i < vecChar.tam(); i++){
                    vecChar.asignar(i, (char)('a'+i));
                    modelo.insertRow(modelo.getRowCount(), new Object[]{vecChar.leer(i)});
                }
                this.jLabelMenor.setText(vecChar.menor()+"");
                this.jLabelMayor.setText(vecChar.mayor()+"");
                this.jLabelPromedio.setText("-");
                break;
                
            case 5: //String
                VectorT<String> vecString = new VectorT(5);
                String [] nombres = {"Juan", "Pedro", "Sergio", "Alma", "Emiliano", "Marcos", "Alfredo", "David", "Abraham", "Isaac"};
                for(int i = 0; i < vecString.tam(); i++){
                    vecString.asignar(i, nombres[random.nextInt(10)]);
                    modelo.insertRow(modelo.getRowCount(), new Object[]{vecString.leer(i)});
                }
                this.jLabelMenor.setText("-");
                this.jLabelMayor.setText("-");
                this.jLabelPromedio.setText("-");
                break;
                
            default: //Sin seleccion
                JOptionPane.showMessageDialog(null, "SELECCIONE UNA OPCIÓN PARA CONTINUAR");
                break;
                
        }
        
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jRadioEnteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEnteroActionPerformed
        limpiar();
        this.jRadioEntero.setSelected(true);
        opc = 1;
    }//GEN-LAST:event_jRadioEnteroActionPerformed

    private void jRadioDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDoubleActionPerformed
        limpiar();
        this.jRadioDouble.setSelected(true);
        opc = 2;
    }//GEN-LAST:event_jRadioDoubleActionPerformed

    private void jRadioFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFloatActionPerformed
        limpiar();
        this.jRadioFloat.setSelected(true);
        opc = 3;
    }//GEN-LAST:event_jRadioFloatActionPerformed

    private void jRadioCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCharActionPerformed
        limpiar();
        this.jRadioChar.setSelected(true);
        opc = 4;
    }//GEN-LAST:event_jRadioCharActionPerformed

    private void jRadioStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioStringActionPerformed
        limpiar();
        this.jRadioString.setSelected(true);
        opc = 5;
    }//GEN-LAST:event_jRadioStringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VectorTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VectorTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VectorTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VectorTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VectorTGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMayor;
    private javax.swing.JLabel jLabelMenor;
    private javax.swing.JLabel jLabelPromedio;
    private javax.swing.JRadioButton jRadioChar;
    private javax.swing.JRadioButton jRadioDouble;
    private javax.swing.JRadioButton jRadioEntero;
    private javax.swing.JRadioButton jRadioFloat;
    private javax.swing.JRadioButton jRadioString;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVector;
    // End of variables declaration//GEN-END:variables
}
