/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfre
 */
public class FormColas extends javax.swing.JFrame {

    /**
     * Creates new form FormColas
     */
    
    Cola cola;
    ColaCircular colaCirc;
    Random random;
    Numero num = new Numero();
    DefaultTableModel modelo;
    int tam = 0, p = 0, u = 0, i = 0;
    
    public FormColas() {
        initComponents();
        random = new Random();
        this.setLocationRelativeTo(null);
        Color color = new Color(130,250,215);
        getContentPane().setBackground(color);
        modelo = (DefaultTableModel) jTableCola.getModel();
        jTableCola.setShowHorizontalLines(true);
        jTableCola.setShowVerticalLines(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoCola = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCola = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerTamaño = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextDato = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVaciar = new javax.swing.JButton();
        jButtonAleatorio = new javax.swing.JButton();
        jButtonLlenar = new javax.swing.JButton();
        jRadioSimple = new javax.swing.JRadioButton();
        jRadioCircular = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableCola.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTableCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTableCola.setRowHeight(40);
        jTableCola.setTableHeader(null);
        jScrollPane1.setViewportView(jTableCola);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COLA:");

        jSpinnerTamaño.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jSpinnerTamaño.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerTamañoStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tamaño de la cola:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Dato a Insertar:");

        jTextDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDatoActionPerformed(evt);
            }
        });

        jButtonInsertar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInsertar.setForeground(new java.awt.Color(204, 255, 255));
        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonEliminar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(204, 255, 255));
        jButtonEliminar.setText("Eliminar dato");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonVaciar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonVaciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVaciar.setForeground(new java.awt.Color(204, 255, 255));
        jButtonVaciar.setText("Vaciar cola");
        jButtonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVaciarActionPerformed(evt);
            }
        });

        jButtonAleatorio.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAleatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAleatorio.setForeground(new java.awt.Color(204, 255, 255));
        jButtonAleatorio.setText("Insertar aleatorio");
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });

        jButtonLlenar.setBackground(new java.awt.Color(0, 0, 153));
        jButtonLlenar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLlenar.setForeground(new java.awt.Color(204, 255, 255));
        jButtonLlenar.setText("Llenar cola");
        jButtonLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLlenarActionPerformed(evt);
            }
        });

        GrupoCola.add(jRadioSimple);
        jRadioSimple.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioSimple.setText("COLA SIMPLE");

        GrupoCola.add(jRadioCircular);
        jRadioCircular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioCircular.setText("COLA CIRCULAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioSimple)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioCircular))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jSpinnerTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTextDato, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonInsertar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonEliminar)
                            .addGap(24, 24, 24)
                            .addComponent(jButtonVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jButtonLlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAleatorio))
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioSimple)
                    .addComponent(jRadioCircular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonVaciar)
                    .addComponent(jButtonAleatorio)
                    .addComponent(jButtonLlenar))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerTamañoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerTamañoStateChanged
        tam = (int)this.jSpinnerTamaño.getValue();
        if(this.jRadioSimple.isSelected())
            cola = new Cola(tam);
        else if(this.jRadioCircular.isSelected())
            colaCirc = new ColaCircular(tam);
        else{
            JOptionPane.showMessageDialog(null, "Selecciona un tipo de cola para continuar");
            tam = 0;
        }
        modelo.setColumnCount(0);
        modelo.setColumnCount(tam);
        p = u = 0;
    }//GEN-LAST:event_jSpinnerTamañoStateChanged

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        if(this.jRadioSimple.isSelected()){
            if(!cola.estaLlena()){
                cola.agregar(Integer.parseInt(this.jTextDato.getText()));
                modelo.setValueAt(this.jTextDato.getText(), 0, p++);
                this.jTextDato.setText("");
                if(cola.estaLlena())
                    p = u = 0;
            }
            else{
                JOptionPane.showMessageDialog(null, "La cola está llena (Overflow)");
            }
        }
        else if(this.jRadioCircular.isSelected()){
            if(!colaCirc.estaLlena()){
                colaCirc.insertar(Integer.parseInt(this.jTextDato.getText()));
                modelo.setValueAt(this.jTextDato.getText(), 0, p++);
                this.jTextDato.setText("");
                if(colaCirc.estaLlena())
                    p = u = 0;
            }
            else{
                JOptionPane.showMessageDialog(null, "La cola está llena (Overflow)");
            }
        }      
    }//GEN-LAST:event_jButtonInsertarActionPerformed
    private void jTextDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDatoActionPerformed
        jButtonInsertarActionPerformed(null);
    }//GEN-LAST:event_jTextDatoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if(this.jRadioSimple.isSelected()){
            if(!cola.estaVacia()){
                cola.extraer(num);
                if(cola.estaVacia()){
                    for(int i = 0; i < tam; i++)
                        modelo.setValueAt("", 0, i);
                    p = u = 0;
                }
                else
                    modelo.setValueAt("-", 0, u++);
            }
            else{
                JOptionPane.showMessageDialog(null, "La cola está vacía (Underflow)");
            }
        }
        else if(this.jRadioCircular.isSelected()){
            if(!colaCirc.estaVacia()){
                colaCirc.eliminar(num);
                if(colaCirc.estaVacia()){
                    for(int i = 0; i < tam; i++)
                        modelo.setValueAt("", 0, i);
                    p = u = 0;
                }
                else{
                    modelo.setValueAt("", 0, p++);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La cola está vacía (Underflow)");
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarActionPerformed
        if(this.jRadioSimple.isSelected()){
            while(!cola.estaVacia())
                cola.extraer(num);
            for(int i = 0; i < tam; i++)
                        modelo.setValueAt("", 0, i);
            p = u = 0;
        }
        else if(this.jRadioCircular.isSelected()){
            while(!colaCirc.estaVacia())
                colaCirc.eliminar(num);
            for(int i = 0; i < tam; i++)
                        modelo.setValueAt("", 0, i);
            p = u = 0;
        }
    }//GEN-LAST:event_jButtonVaciarActionPerformed

    private void jButtonLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLlenarActionPerformed
        if(this.jRadioSimple.isSelected()){
            while(!cola.estaLlena()){
                int rnd = random.nextInt(900)+100;
                cola.agregar(rnd);
                modelo.setValueAt(rnd, 0, p++);
            }
            p = u = 0;
        }
        else if(this.jRadioCircular.isSelected()){
            while(!colaCirc.estaLlena()){
                int rnd = random.nextInt(900)+100;
                colaCirc.insertar(rnd);
                modelo.setValueAt(rnd, 0, p++);
            }
            p = u = 0;
        }
        
    }//GEN-LAST:event_jButtonLlenarActionPerformed

    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        if(this.jRadioSimple.isSelected()){
            if(!cola.estaLlena()){
                int rnd = random.nextInt(900)+100;
                cola.agregar(rnd);
                modelo.setValueAt(rnd, 0, p++);
                if(cola.estaLlena())
                    p = u = 0;
            }
            else{
                JOptionPane.showMessageDialog(null, "La cola está llena (Overflow)");
            }
        }
        else if(this.jRadioCircular.isSelected()){
            if(!colaCirc.estaLlena()){
                int rnd = random.nextInt(900)+100;
                colaCirc.insertar(rnd);
                modelo.setValueAt(rnd, 0, p++);
                if(colaCirc.estaLlena())
                    p = u = 0;
            }
            else{
                JOptionPane.showMessageDialog(null, "La cola está llena (Overflow)");
            }
        }
        
    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormColas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoCola;
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonLlenar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioCircular;
    private javax.swing.JRadioButton jRadioSimple;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerTamaño;
    private javax.swing.JTable jTableCola;
    private javax.swing.JTextField jTextDato;
    // End of variables declaration//GEN-END:variables
}
