/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfre
 */
public class FormMultiplicacionMatrices extends javax.swing.JFrame {

    Random random = new Random();
    DefaultTableModel mMA, mMB, mMC;
    int matA [][] = new int [0][0];
    int matB [][] = new int [0][0];
    int matC [][] = new int [0][0];
    
    /**
     * Creates new form FormMultiplicacionMatrices
     */
    public FormMultiplicacionMatrices() {
        initComponents();
        this.setLocationRelativeTo(null);
        Color color  = new Color(255, 255, 255);
        this.getContentPane().setBackground(color);
        mMA = (DefaultTableModel)this.jTableMatrizA.getModel();
        mMB = (DefaultTableModel)this.jTableMatrizB.getModel();
        mMC = (DefaultTableModel)this.jTableMatrizC.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoMA = new javax.swing.ButtonGroup();
        GrupoMB = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatrizA = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMatrizB = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMatrizC = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerRA = new javax.swing.JSpinner();
        jSpinnerCA = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerRB = new javax.swing.JSpinner();
        jSpinnerCB = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jRadioXDefaultA = new javax.swing.JRadioButton();
        jRadioCapturarlosA = new javax.swing.JRadioButton();
        jRadioAleatoriosA = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jRadioXDefaultB = new javax.swing.JRadioButton();
        jRadioCapturarlosB = new javax.swing.JRadioButton();
        jRadioAleatoriosB = new javax.swing.JRadioButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableMatrizA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTableMatrizA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableMatrizA);

        jTableMatrizB.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTableMatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMatrizB);

        jTableMatrizC.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTableMatrizC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableMatrizC);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MULTIPLICACION DE MATRICES");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Puentes Vargas Alfredo - 22130803");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MATRIZ A");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MATRIZ B");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MATRIZ C");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("*");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("=");

        jLabel8.setText("No. Renglones");

        jLabel9.setText("No. Columnas");

        jSpinnerRA.setModel(new javax.swing.SpinnerNumberModel(3, 3, 5, 1));

        jSpinnerCA.setModel(new javax.swing.SpinnerNumberModel(3, 3, 5, 1));

        jLabel10.setText("No. Renglones");

        jLabel11.setText("No. Columnas");

        jSpinnerRB.setModel(new javax.swing.SpinnerNumberModel(3, 3, 5, 1));

        jSpinnerCB.setModel(new javax.swing.SpinnerNumberModel(3, 3, 5, 1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel12.setText("DATOS");

        GrupoMA.add(jRadioXDefaultA);
        jRadioXDefaultA.setText("X DEFAULT");
        jRadioXDefaultA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioXDefaultAActionPerformed(evt);
            }
        });

        GrupoMA.add(jRadioCapturarlosA);
        jRadioCapturarlosA.setText("CAPTURARLOS");
        jRadioCapturarlosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCapturarlosAActionPerformed(evt);
            }
        });

        GrupoMA.add(jRadioAleatoriosA);
        jRadioAleatoriosA.setText("ALEATORIOS");
        jRadioAleatoriosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAleatoriosAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioAleatoriosA, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioCapturarlosA)
                    .addComponent(jRadioXDefaultA)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioXDefaultA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioCapturarlosA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioAleatoriosA)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));

        jLabel15.setText("DATOS");

        GrupoMB.add(jRadioXDefaultB);
        jRadioXDefaultB.setText("X DEFAULT");
        jRadioXDefaultB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioXDefaultBActionPerformed(evt);
            }
        });

        GrupoMB.add(jRadioCapturarlosB);
        jRadioCapturarlosB.setText("CAPTURARLOS");
        jRadioCapturarlosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCapturarlosBActionPerformed(evt);
            }
        });

        GrupoMB.add(jRadioAleatoriosB);
        jRadioAleatoriosB.setText("ALEATORIOS");
        jRadioAleatoriosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAleatoriosBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioAleatoriosB, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioCapturarlosB)
                    .addComponent(jRadioXDefaultB)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioXDefaultB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioCapturarlosB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioAleatoriosB)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButtonMultiplicar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMultiplicar.setText("MULTIPLICAR");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jButtonBorrar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(255, 61, 61));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinnerCA)
                                            .addComponent(jSpinnerRA, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSpinnerRB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerCB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void multiplicar(){
        if(matA[0].length == matB.length){
            matC = new int [matA.length][matB[0].length];
            for(int i = 0; i < matA.length; i++){
                for(int j = 0; j < matB[0].length; j++){
                    matC[i][j] = 0;
                    for(int k = 0; k < matB[0].length; k++)
                        matC[i][j] += matA[i][k] * matB[k][j];
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No es posible multiplicar las matrices!");
        }
    }
    
    private void jRadioXDefaultAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioXDefaultAActionPerformed
        //X DEFECTO
        matA = new int [(int)this.jSpinnerRA.getValue()][(int)this.jSpinnerCA.getValue()];
        mMA.setRowCount(matA.length);
        mMA.setColumnCount(matA[0].length);
        
        int contador = 1;
        for(int i = 0; i < matA.length; i++){
            for(int j = 0; j < matA[0].length; j++){
                matA[i][j] = contador;
                mMA.setValueAt(Integer.toString(matA[i][j]), i, j);
                contador++;
            }
        }
    }//GEN-LAST:event_jRadioXDefaultAActionPerformed

    private void jRadioCapturarlosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCapturarlosAActionPerformed
        //CAPTURARLOS
        matA = new int [(int)this.jSpinnerRA.getValue()][(int)this.jSpinnerCA.getValue()];
        mMA.setRowCount(matA.length);
        mMA.setColumnCount(matA[0].length);
        
        for(int i = 0; i < matA.length; i++){
            for(int j = 0; j < matA[0].length; j++){
                matA[i][j] = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el valor de " + i + "," + j + ":"));
                mMA.setValueAt(Integer.toString(matA[i][j]), i, j);
            }
        }
    }//GEN-LAST:event_jRadioCapturarlosAActionPerformed

    private void jRadioAleatoriosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAleatoriosAActionPerformed
        //ALEATORIOS
        matA = new int [(int)this.jSpinnerRA.getValue()][(int)this.jSpinnerCA.getValue()];
        mMA.setRowCount(matA.length);
        mMA.setColumnCount(matA[0].length);
        
        for(int i = 0; i < matA.length; i++){
            for(int j = 0; j < matA[0].length; j++){
                matA[i][j] = random.nextInt(90)+10;
                mMA.setValueAt(Integer.toString(matA[i][j]), i, j);
            }
        }
    }//GEN-LAST:event_jRadioAleatoriosAActionPerformed

    private void jRadioXDefaultBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioXDefaultBActionPerformed
        //X DEFECTO
        matB = new int [(int)this.jSpinnerRB.getValue()][(int)this.jSpinnerCB.getValue()];
        mMB.setRowCount(matB.length);
        mMB.setColumnCount(matB[0].length);
        
        int contador = 1;
        for(int i = 0; i < matB.length; i++){
            for(int j = 0; j < matB[0].length; j++){
                matB[i][j] = contador;
                mMB.setValueAt(Integer.toString(matB[i][j]), i, j);
                contador++;
            }
        }
    }//GEN-LAST:event_jRadioXDefaultBActionPerformed

    private void jRadioCapturarlosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCapturarlosBActionPerformed
        //CAPTURARLOS
        matB = new int [(int)this.jSpinnerRB.getValue()][(int)this.jSpinnerCB.getValue()];
        mMB.setRowCount(matB.length);
        mMB.setColumnCount(matB[0].length);
        
        for(int i = 0; i < matB.length; i++){
            for(int j = 0; j < matB[0].length; j++){
                matB[i][j] = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el valor de " + i + "," + j + ":"));
                mMB.setValueAt(Integer.toString(matB[i][j]), i, j);
            }
        }
    }//GEN-LAST:event_jRadioCapturarlosBActionPerformed

    private void jRadioAleatoriosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAleatoriosBActionPerformed
        //ALEATORIOS
        matB = new int [(int)this.jSpinnerRB.getValue()][(int)this.jSpinnerCB.getValue()];
        mMB.setRowCount(matB.length);
        mMB.setColumnCount(matB[0].length);
        
        for(int i = 0; i < matB.length; i++){
            for(int j = 0; j < matB[0].length; j++){
                matB[i][j] = random.nextInt(90)+10;
                mMB.setValueAt(Integer.toString(matB[i][j]), i, j);
            }
        }
    }//GEN-LAST:event_jRadioAleatoriosBActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        //MULTIPLICAR
        multiplicar();
        mMC.setRowCount(matC.length);
        mMC.setColumnCount(matC[0].length);
        
        for(int i = 0; i < matC.length; i++){
            for(int j = 0; j < matC[0].length; j++){
                mMC.setValueAt(Integer.toString(matC[i][j]), i, j);
            }
        }
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        //BORRAR
        mMA.setColumnCount(0);
        mMB.setColumnCount(0);
        mMC.setColumnCount(0);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //SALIR
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMultiplicacionMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMultiplicacionMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMultiplicacionMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMultiplicacionMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMultiplicacionMatrices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoMA;
    private javax.swing.ButtonGroup GrupoMB;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioAleatoriosA;
    private javax.swing.JRadioButton jRadioAleatoriosB;
    private javax.swing.JRadioButton jRadioCapturarlosA;
    private javax.swing.JRadioButton jRadioCapturarlosB;
    private javax.swing.JRadioButton jRadioXDefaultA;
    private javax.swing.JRadioButton jRadioXDefaultB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerCA;
    private javax.swing.JSpinner jSpinnerCB;
    private javax.swing.JSpinner jSpinnerRA;
    private javax.swing.JSpinner jSpinnerRB;
    private javax.swing.JTable jTableMatrizA;
    private javax.swing.JTable jTableMatrizB;
    private javax.swing.JTable jTableMatrizC;
    // End of variables declaration//GEN-END:variables
}
