/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guest
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    
    DefaultTableModel modelo;
    int [] vec;
    Numero interc = new Numero();
    Numero comp = new Numero();
    
    public form1() {
        initComponents();
        this.setLocationRelativeTo(null);
        Color color = new Color(1,1,1);
        this.getContentPane().setBackground(color);
        modelo = (DefaultTableModel) this.jTableDatos.getModel();
        modelo.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDatos = new javax.swing.ButtonGroup();
        grupoOrden = new javax.swing.ButtonGroup();
        grupoMetodo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerElementos = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioCapturar = new javax.swing.JRadioButton();
        jRadioAleatorios = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioAscendente = new javax.swing.JRadioButton();
        jRadioDescendente = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioBurbuja = new javax.swing.JRadioButton();
        jRadioBurbujaSeñal = new javax.swing.JRadioButton();
        jRadioShaker = new javax.swing.JRadioButton();
        jRadioShell = new javax.swing.JRadioButton();
        jRadioShell2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelComparaciones = new javax.swing.JLabel();
        jLabelIntercambios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. de Elementos");

        jSpinnerElementos.setModel(new javax.swing.SpinnerNumberModel(5, 5, 500, 1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("DATOS");

        grupoDatos.add(jRadioCapturar);
        jRadioCapturar.setText("Capturar");
        jRadioCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCapturarActionPerformed(evt);
            }
        });

        grupoDatos.add(jRadioAleatorios);
        jRadioAleatorios.setText("Aleatorios");
        jRadioAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAleatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jRadioCapturar)
                    .addComponent(jRadioAleatorios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioCapturar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioAleatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("ORDEN");

        grupoOrden.add(jRadioAscendente);
        jRadioAscendente.setText("Ascendente");

        grupoOrden.add(jRadioDescendente);
        jRadioDescendente.setText("Descendente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jRadioAscendente)
                    .addComponent(jRadioDescendente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioAscendente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioDescendente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setText("METODO");

        grupoMetodo.add(jRadioBurbuja);
        jRadioBurbuja.setText("Burbuja Simple");
        jRadioBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBurbujaActionPerformed(evt);
            }
        });

        grupoMetodo.add(jRadioBurbujaSeñal);
        jRadioBurbujaSeñal.setText("Burbuja con señal");
        jRadioBurbujaSeñal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBurbujaSeñalActionPerformed(evt);
            }
        });

        grupoMetodo.add(jRadioShaker);
        jRadioShaker.setText("Shaker");
        jRadioShaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioShakerActionPerformed(evt);
            }
        });

        grupoMetodo.add(jRadioShell);
        jRadioShell.setText("Shell 1");
        jRadioShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioShellActionPerformed(evt);
            }
        });

        grupoMetodo.add(jRadioShell2);
        jRadioShell2.setText("Shell 2");
        jRadioShell2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioShell2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jRadioBurbuja)
                    .addComponent(jRadioBurbujaSeñal)
                    .addComponent(jRadioShaker)
                    .addComponent(jRadioShell)
                    .addComponent(jRadioShell2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioBurbuja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioBurbujaSeñal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioShaker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioShell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioShell2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDatos);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No. Comparaciones:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Intercambios:");

        jLabelComparaciones.setBackground(new java.awt.Color(255, 255, 255));
        jLabelComparaciones.setOpaque(true);

        jLabelIntercambios.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIntercambios.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabelComparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIntercambios, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jSpinnerElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelComparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIntercambios, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCapturarActionPerformed
        modelo.setRowCount(Integer.valueOf(this.jSpinnerElementos.getValue().toString()));
        for(int i = 0; i < modelo.getRowCount(); i++)
            this.jTableDatos.setValueAt("", i, 0);
        this.grupoOrden.clearSelection();
        this.grupoMetodo.clearSelection();
    }//GEN-LAST:event_jRadioCapturarActionPerformed

    private void jRadioAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAleatoriosActionPerformed
        modelo.setRowCount(Integer.valueOf(this.jSpinnerElementos.getValue().toString()));
        Random random = new Random();
        for(int r = 0; r < modelo.getRowCount(); r++)
            modelo.setValueAt(random.nextInt(900)+100, r, 0);
        this.grupoOrden.clearSelection();
        this.grupoMetodo.clearSelection();
    }//GEN-LAST:event_jRadioAleatoriosActionPerformed

    private void jRadioBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBurbujaActionPerformed
        //BURBUJA SIMPLE
        this.jLabelComparaciones.setText("");
        this.jLabelIntercambios.setText("");
        vec = new int [this.jTableDatos.getRowCount()];
        
        if(this.jRadioAscendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.BurbujaAsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else if(this.jRadioDescendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.BurbujaDsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else
            JOptionPane.showMessageDialog(null, "SELECCIONA UN ORDEN PARA CONTINUAR");
        
        this.grupoOrden.clearSelection();
        this.grupoMetodo.clearSelection();
    }//GEN-LAST:event_jRadioBurbujaActionPerformed

    private void jRadioBurbujaSeñalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBurbujaSeñalActionPerformed
        //BURBUJA CON SEÑAL
        this.jLabelComparaciones.setText("");
        this.jLabelIntercambios.setText("");
        vec = new int [this.jTableDatos.getRowCount()];
        
        if(this.jRadioAscendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.BurbujaConSeñalAsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else if(this.jRadioDescendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.BurbujaConSeñalDsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else
            JOptionPane.showMessageDialog(null, "SELECCIONA UN ORDEN PARA CONTINUAR");
        
        this.grupoOrden.clearSelection();
        this.grupoMetodo.clearSelection();
    }//GEN-LAST:event_jRadioBurbujaSeñalActionPerformed

    private void jRadioShakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioShakerActionPerformed
        //SHAKER
        this.jLabelComparaciones.setText("");
        this.jLabelIntercambios.setText("");
        vec = new int [this.jTableDatos.getRowCount()];
                        
        if(this.jRadioAscendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.shaker_sortAsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else if(this.jRadioDescendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.shaker_sortDsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else
            JOptionPane.showMessageDialog(null, "SELECCIONA UN ORDEN PARA CONTINUAR");
        
        this.grupoOrden.clearSelection();
        this.grupoMetodo.clearSelection();
    }//GEN-LAST:event_jRadioShakerActionPerformed

    private void jRadioShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioShellActionPerformed
        //SHELL
        this.jLabelComparaciones.setText("");
        this.jLabelIntercambios.setText("");
        vec = new int [this.jTableDatos.getRowCount()];
                        
        if(this.jRadioAscendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.shellAsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else if(this.jRadioDescendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.shellDsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else
            JOptionPane.showMessageDialog(null, "SELECCIONA UN ORDEN PARA CONTINUAR");
        
        this.grupoOrden.clearSelection();
        this.grupoMetodo.clearSelection();
    }//GEN-LAST:event_jRadioShellActionPerformed

    private void jRadioShell2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioShell2ActionPerformed
        //SHELL2
        this.jLabelComparaciones.setText("");
        this.jLabelIntercambios.setText("");
        vec = new int [this.jTableDatos.getRowCount()];
                        
        if(this.jRadioAscendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.shell2Asc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else if(this.jRadioDescendente.isSelected()){
            for(int i = 0; i < vec.length; i++)
                vec[i] = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            Ordenamiento.shell2Dsc(vec, comp, interc);
            for(int i = 0; i < vec.length; i++)
                modelo.setValueAt(vec[i], i, 0);
            this.jLabelComparaciones.setText(comp.num+"");
            this.jLabelIntercambios.setText(interc.num+"");
        }
        else
            JOptionPane.showMessageDialog(null, "SELECCIONA UN ORDEN PARA CONTINUAR");
        
        this.grupoOrden.clearSelection();
        this.grupoMetodo.clearSelection();
    }//GEN-LAST:event_jRadioShell2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoDatos;
    private javax.swing.ButtonGroup grupoMetodo;
    private javax.swing.ButtonGroup grupoOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelComparaciones;
    private javax.swing.JLabel jLabelIntercambios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioAleatorios;
    private javax.swing.JRadioButton jRadioAscendente;
    private javax.swing.JRadioButton jRadioBurbuja;
    private javax.swing.JRadioButton jRadioBurbujaSeñal;
    private javax.swing.JRadioButton jRadioCapturar;
    private javax.swing.JRadioButton jRadioDescendente;
    private javax.swing.JRadioButton jRadioShaker;
    private javax.swing.JRadioButton jRadioShell;
    private javax.swing.JRadioButton jRadioShell2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerElementos;
    private javax.swing.JTable jTableDatos;
    // End of variables declaration//GEN-END:variables
}
