package Clases;


import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alfre
 */
public class FormaPedido extends javax.swing.JFrame {

    /**
     * Creates new form FormaPedido
     */
    
    DefaultTableModel modeloTabla;
    Random random  = new Random();
    ArchivosBinarios archivo = new ArchivosBinarios();
    Producto productos[];
    Producto aux[] = new Producto[0];
    
    double precios[] = {50.00, 60.00, 75.00, 35.00, 40.00, 55.00, 60.00, 40.00, 30.00, 45.00, 40.00, 30.00};
    String descripciones[] = {"Orden de carnitas con complementos para tacos", "Chiles rellenos bañados en salsa de nuez", "Carne adobada con complementos para tacos",
    "Enchiladas de pollo en salsa roja", "Enchiladas de pollo en salsa verde", "Filete de pescado sazonado con finas hierbas", "Mole poblano con arroz blanco",
    "Pozole rojo con carne de pollo", "Orden de sopes con complementos", "Orden de tacos de pastor con complementos", "Orden de tacos de suadero con compelmentos", "Tamales oaxaqueños variados"};
    
    public FormaPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
        Color color = new Color(50,0,100);
        this.getContentPane().setBackground(color);
        modeloTabla = (DefaultTableModel) jTablePedido.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoOrdenar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jButtonMenu = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonQuitar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioCodigo = new javax.swing.JRadioButton();
        jRadioNombre = new javax.swing.JRadioButton();
        jRadioPrecio = new javax.swing.JRadioButton();
        jButtonBusCodigo = new javax.swing.JButton();
        jButtonBusProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REALIZAR UN PEDIDO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCTO:");

        jComboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(SELECCIONAR)", "CARNITAS", "CHILES EN NOGADA", "COCHINITA PIBIL", "ENCHILADAS ROJAS", "ENCHILADAS VERDES", "FILETE DE PESCADO", "MOLE CON ARROZ", "POZOLE", "SOPES", "TACOS AL PASTOR", "TACOS DE SUADERO", "TAMALES", " " }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANTIDAD:");

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButtonMenu.setBackground(new java.awt.Color(255, 204, 255));
        jButtonMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMenu.setForeground(new java.awt.Color(102, 0, 204));
        jButtonMenu.setText("MENÚ");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jButtonAgregar.setBackground(new java.awt.Color(255, 204, 255));
        jButtonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(102, 0, 204));
        jButtonAgregar.setText("AGREGAR");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonQuitar.setBackground(new java.awt.Color(255, 204, 255));
        jButtonQuitar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonQuitar.setForeground(new java.awt.Color(102, 0, 204));
        jButtonQuitar.setText("QUITAR");
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ORDENAR POR:");

        GrupoOrdenar.add(jRadioCodigo);
        jRadioCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioCodigo.setText("Código");
        jRadioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCodigoActionPerformed(evt);
            }
        });

        GrupoOrdenar.add(jRadioNombre);
        jRadioNombre.setForeground(new java.awt.Color(255, 255, 255));
        jRadioNombre.setText("Nombre");
        jRadioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNombreActionPerformed(evt);
            }
        });

        GrupoOrdenar.add(jRadioPrecio);
        jRadioPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jRadioPrecio.setText("Precio");
        jRadioPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPrecioActionPerformed(evt);
            }
        });

        jButtonBusCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBusCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBusCodigo.setForeground(new java.awt.Color(153, 0, 153));
        jButtonBusCodigo.setText("BUSCAR CÓDIGO");
        jButtonBusCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusCodigoActionPerformed(evt);
            }
        });

        jButtonBusProducto.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBusProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBusProducto.setForeground(new java.awt.Color(153, 0, 153));
        jButtonBusProducto.setText("BUSCAR PRODUCTO");
        jButtonBusProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBusProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBusCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jRadioCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioPrecio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMenu)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBusProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBusCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioCodigo)
                    .addComponent(jRadioNombre)
                    .addComponent(jRadioPrecio))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTablePedido.setBackground(new java.awt.Color(255, 204, 255));
        jTablePedido.setForeground(new java.awt.Color(102, 0, 204));
        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CANTIDAD", "PRODUCTO", "DESCRIPCION", "PRECIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePedido);
        if (jTablePedido.getColumnModel().getColumnCount() > 0) {
            jTablePedido.getColumnModel().getColumn(0).setResizable(false);
            jTablePedido.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTablePedido.getColumnModel().getColumn(1).setResizable(false);
            jTablePedido.getColumnModel().getColumn(1).setPreferredWidth(25);
            jTablePedido.getColumnModel().getColumn(2).setResizable(false);
            jTablePedido.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTablePedido.getColumnModel().getColumn(3).setResizable(false);
            jTablePedido.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTablePedido.getColumnModel().getColumn(4).setResizable(false);
            jTablePedido.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL A PAGAR:");

        jLabelTotal.setForeground(new java.awt.Color(255, 102, 255));
        jLabelTotal.setText("$00.00 MXN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelTotal))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void calcularPrecio(){
        double totalPagar = 0;
        for(int i = 0; i < modeloTabla.getRowCount(); i++){
                totalPagar += ((double)modeloTabla.getValueAt(i, 4) * (int)modeloTabla.getValueAt(i, 1));
            }
        this.jLabelTotal.setText("$"+totalPagar+"MXN");
    }
    
    public void guardarEnArreglo(Producto p){
        productos = new Producto[aux.length+1];
        for(int i = 0; i < aux.length; i++)
            productos[i] = aux[i];
        productos[productos.length-1] = p;
        aux = productos;
    }
    
    public void borrarDeArreglo(int pos){
        productos = new Producto[aux.length-1];
        for(int i = 0; i < pos; i++)
            productos[i] = aux[i];
        for(int i = aux.length-2; i >= pos; i--)
            productos[i] = aux[i+1];
        aux = productos;
            
    }
    
    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        if(jComboProducto.getSelectedIndex() == 0 || jSpinnerCantidad.getValue().equals(0)){
            JOptionPane.showMessageDialog(null, "ENTRADA NO VALIDA\nLlene todos los campos para continuar");
        }
        else{
            Producto producto  = new Producto(random.nextInt(9000)+1000, (int)this.jSpinnerCantidad.getValue(), (String)this.jComboProducto.getSelectedItem(),
            descripciones[this.jComboProducto.getSelectedIndex()-1], precios[this.jComboProducto.getSelectedIndex()-1]);
            guardarEnArreglo(producto);
            Ordenamiento.ordenarCodigoAsc(productos, 0, productos.length-1);
            this.jRadioCodigo.setSelected(true);
            archivo.guardarVecEnArchivo("pedidos.bin", productos);
            archivo.leerArchivoEnTabla("pedidos.bin", jTablePedido);
            calcularPrecio();
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        try{
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el código del producto a quitar:"));
            int pos = Busquedas.binariaCodigo(productos, codigo);
            if(pos != -1){
                borrarDeArreglo(pos);
                archivo.guardarVecEnArchivo("pedidos.bin", productos);
                archivo.leerArchivoEnTabla("pedidos.bin", jTablePedido);
                calcularPrecio();
            }
            else
                JOptionPane.showMessageDialog(null, "Codigo del producto no encontrado");
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Código no válido");
        }
    }//GEN-LAST:event_jButtonQuitarActionPerformed

    private void jButtonBusCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusCodigoActionPerformed
        try{
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE EL CÓDIGO DEL PRODUCTO A BUSCAR:\n(Ingrese 0 para buscar todos los productos)"));
            int pos = Busquedas.binariaCodigo(productos, codigo);
            if(pos != -1){
                modeloTabla.setRowCount(1);
                this.jTablePedido.setValueAt(productos[pos].codigo, 0, 0);
                this.jTablePedido.setValueAt(productos[pos].cantidad, 0, 1);
                this.jTablePedido.setValueAt(productos[pos].nombre, 0, 2);
                this.jTablePedido.setValueAt(productos[pos].descripcion, 0, 3);
                this.jTablePedido.setValueAt(productos[pos].precio, 0, 4);
            }
            else if(codigo == 0){
                archivo.guardarVecEnArchivo("pedidos.bin", productos);
                archivo.leerArchivoEnTabla("pedidos.bin", jTablePedido);
            }
            else
                JOptionPane.showMessageDialog(null, "Codigo del producto no encontrado");
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Código no válido");
        }
    }//GEN-LAST:event_jButtonBusCodigoActionPerformed

    private void jButtonBusProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusProductoActionPerformed
        String nombre = JOptionPane.showInputDialog(null, "INGRESE EL NOMBRE DEL PRODUCTO A BUSCAR:\n(Ingrese 0 para buscar todos los productos)");
        if(nombre.equals("0")){
            archivo.guardarVecEnArchivo("pedidos.bin", productos);
            archivo.leerArchivoEnTabla("pedidos.bin", jTablePedido);
        }
        else{
            int pos = Busquedas.binariaNombre(productos, nombre.toUpperCase());
            if(pos != -1){
                modeloTabla.setRowCount(1);
                this.jTablePedido.setValueAt(productos[pos].codigo, 0, 0);
                this.jTablePedido.setValueAt(productos[pos].cantidad, 0, 1);
                this.jTablePedido.setValueAt(productos[pos].nombre, 0, 2);
                this.jTablePedido.setValueAt(productos[pos].descripcion, 0, 3);
                this.jTablePedido.setValueAt(productos[pos].precio, 0, 4);
            }
            else
                JOptionPane.showMessageDialog(null, "Nombre del producto no encontrado");
        }
    }//GEN-LAST:event_jButtonBusProductoActionPerformed

    private void jRadioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNombreActionPerformed
        Ordenamiento.ordenarNombreAsc(productos, 0, productos.length-1);
        archivo.guardarVecEnArchivo("pedidos.bin", productos);
        archivo.leerArchivoEnTabla("pedidos.bin", jTablePedido);
    }//GEN-LAST:event_jRadioNombreActionPerformed

    private void jRadioPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPrecioActionPerformed
        Ordenamiento.ordenarPrecioAsc(productos, 0, productos.length-1);
        archivo.guardarVecEnArchivo("pedidos.bin", productos);
        archivo.leerArchivoEnTabla("pedidos.bin", jTablePedido);
    }//GEN-LAST:event_jRadioPrecioActionPerformed

    private void jRadioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCodigoActionPerformed
        Ordenamiento.ordenarCodigoAsc(productos, 0, productos.length-1);
        archivo.guardarVecEnArchivo("pedidos.bin", productos);
        archivo.leerArchivoEnTabla("pedidos.bin", jTablePedido);
    }//GEN-LAST:event_jRadioCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoOrdenar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBusCodigo;
    private javax.swing.JButton jButtonBusProducto;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JComboBox<String> jComboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioCodigo;
    private javax.swing.JRadioButton jRadioNombre;
    private javax.swing.JRadioButton jRadioPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTablePedido;
    // End of variables declaration//GEN-END:variables
}
